<?php
// Variables
return [
  "creatorName" => "ThemeSelection",
  "creatorUrl" => "https://themeselection.com",
  "templateName" => "Store Buddy",
  "templateSuffix" => "Store Buddy",
  "templateVersion" => "4.0.0",
  "templateFree" => false,
  "templateDescription" => "Most Powerful & Comprehensive Bootstrap 5 + Laravel HTML Admin Dashboard Template built for developers!",
  "templateKeyword" => "dashboard, bootstrap 5 dashboard, bootstrap 5 design, bootstrap 5",
  "licenseUrl" => "https://themeselection.com/license/",
  "livePreview" => "https://demos.themeselection.com/sneat-bootstrap-html-laravel-admin-template/demo-1/",
  "productPage" => "https://themeselection.com/item/sneat-dashboard-pro-laravel/",
  "support" => "https://themeselection.com/support/",
  "adminTemplates" => "https://themeselection.com/item/category/admin-templates/",
  "bootstrapDashboard" => "https://themeselection.com/item/category/bootstrap-admin-templates/",
  "ogTitle" => "Sneat Bootstrap 5 HTML + Laravel Admin Template by ThemeSelection",
  "ogImage" => "https://ts-assets.b-cdn.net/ts-assets/sneat/sneat-bootstrap-laravel-admin-template/marketing/sneat-bootstrap-laravel-admin-template-smm.png",
  "ogType" => "product",
  "documentation" => "https://demos.themeselection.com/sneat-bootstrap-html-admin-template/documentation",
  "changelog" => "https://demos.themeselection.com/sneat-bootstrap-html-laravel-admin-template/changelog.html",
  "repository" => "https://github.com/themeselection/sneat-bootstrap-html-laravel-admin-template",
  "gitRepo" => "sneat-bootstrap-html-laravel-admin-template",
  "gitRepoAccess" => "https://tools.themeselection.com/github/github-access",
  "githubFreeUrl" => "https://github.com/themeselection",
  "facebookUrl" => "https://www.facebook.com/ThemeSelections/",
  "twitterUrl" => "https://x.com/Theme_Selection",
  "githubUrl" => "https://github.com/themeselection",
  "dribbbleUrl" => "https://dribbble.com/themeselection",
  "instagramUrl" => "https://www.instagram.com/themeselection/"
];
